package try_in;

import java.io.IOException;

public class A_test454 {

	public void foo() {
		try {
			/*[*/throw new IOException("Message");/*]*/
		} catch (Exception e) {
		}
	}
}
